image: docker

stages:
  - deploy

before_script:
  - apk update && apk add git

mirror:
  stage: deploy
  script:
    - git push --mirror https://GITHUB_USERNAME:GITHUB_PASSWORD@github.com/thisisbliss/bliss-go.git