image: indiehosters/git

stages:
  - deploy

mirror:
  stage: deploy
  script:
  - mkdir "${HOME}/.ssh"
  - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
  - chmod 700 "${HOME}/.ssh/id_rsa"
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - git push --mirror git@github.com/thisisbliss/bliss-go.git